### ISSUE TITLE
[RELEASE] KES Release 2024-02-29T08-12-28Z

### ISSUE THREAD

**Issue by djwfyi** [minio/kes-docs#49]
KES Release [2024-02-29T08-12-28Z](https://github.com/minio/kes/releases/tag/2024-02-29T08-12-28Z) has changes the impact the docs:

- [x] KES now has a Grafana dashboard. [PR #447](https://github.com/minio/kes/pull/447)
       Add to the monitoring docs.
- [x] Adds HMAC API and updates ciphertext cryptography [PR #433](https://github.com/minio/kes/pull/433)
- [x] Removes enclaves in CLI commands [PR #434](https://github.com/minio/kes/pull/434)
        Note: This PR is titled tests for #433, but it also removes several commands and -e flags in the file changes.
- [x] Note that after upgrading to this version, you cannot downgrade to an earlier version due to the ciphertext updates.
