### ISSUE TITLE
KES release 2024-06-17T15-47-05Z

### ISSUE THREAD

**Issue by djwfyi** [minio/kes-docs#58]
KES [Release 2024-06-17T15-47-05Z](https://github.com/minio/kes/releases/tag/2024-06-17T15-47-05Z) has changes that impact the docs:

- [x] Adds new `kes ls` command ([PR #464](https://github.com/minio/kes/pull/464))
- [x] Updates to how `kes identity` functions ([PR #461](https://github.com/minio/kes/pull/461))
- [x] Upgrade for Azure SDK _may_ impact docs ([PR #459](https://github.com/minio/kes/pull/459))
- [x] Fix for `kes identity new` example ([PR #467](https://github.com/minio/kes/pull/467))

**Comment by djwfyi** [comment]
459 does not appear to have any doc impacts
